### ISSUE TITLE
[REQ] Make DatapackScanner a submodule

### ISSUE THREAD

**Issue by CanInBad** [Alexofp/BDCCMods#36]
## Pro

- Reduce file size for those who don't want DatapackScanner when contributing 
- Is a sperate repo

## Cons

- Is a sperate repo
- Harder to maintain, if changes and commit is made in DataScanner, you also have to commit changes on this repository

**Comment by Alexofp** [comment]
I think it's small enough x3. And it's just tooooo convenient to have in the same folder, I can press a single button and it does all the work..

**Comment by CanInBad** [comment]
> it's just tooooo convenient to have in the same folder  

I agree, that's why I suggested to make it submodule instead. Submodule allow you to keep a git repository as a subdirectory in another git repo, this doesn't add file size because it is technically only a reference to git commit, other contributors can choose if they want to init it or not. This doesn't affect you at all unless you make changes to DatapackScanner (since you'll need to make 2 commits, one for DatapackScanner repo and one for master repo because reference changes).

Here is an example what if you make it a submodule: https://github.com/CanInBad/BDCCMods/tree/submoduleEX

It is okay if you don't want to do such, you may close this and #37 as not planned if you don't want to do it.

**Comment by Alexofp** [comment]
Yeah, I'd rather keep it as is x3
